# Generated by Django 5.2.8 on 2025-12-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('instrument_type', models.CharField(max_length=50, verbose_name='Тип інструменту')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('material', models.CharField(max_length=50, verbose_name='Матеріал')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна ($)')),
            ],
        ),
    ]
